### ISSUE TITLE
As an InfraSonar user I want to see detailed information of Windows shares on Microsoft Windows hosts.

### ISSUE THREAD

**Issue by riklempens** [infrasonar/wmi-probe#1]
Windows share information can be retrieved using the `Win32_Share` class.

Interesting properties:

- Caption (string)
- Description (string)
- Status (string)
- AllowMaximum (boolean);
- MaximumAllowed (uint32)
- Name (string)
- Path (string)
- Type (uint32)

For `Type` it would be nice if the `unint32` value is "translated" to human readable equivalent:

- Disk Drive (0)
- Print Queue (1)
- Device (2)
- IPC (3)
- Disk Drive Admin (2147483648)
- Print Queue Admin (2147483649)
- Device Admin (2147483650)
- IPC Admin (2147483651)

**Comment by joente** [comment]
This will be the new type: 

```javascript
new_type('ntDomain', 'share', true, [
    {name: 'name', data_type: String, required: true},
    {name: 'Caption', data_type: String, required: true},
    {name: 'Description', data_type: String, required: true},
    {name: 'Status', data_type: String, required: true},
    {name: 'AllowMaximum', data_type: Boolean, required: true},
    {name: 'MaximumAllowed', data_type: Int, required: true},
    {name: 'Path', data_type: String, required: true},
    {name: 'Type', data_type: String, required: true},
]);
```
