### ISSUE TITLE
`Win32_ServerFeature` does not exist on non Windows server operating systems.

### ISSUE THREAD

**Issue by riklempens** [infrasonar/wmi-probe#13]
When using the wmi-probe on a Windows 11 asset the following error occurs:
```
invalid class: Win32_ServerFeature
```
This makes sense as `Win32_ServerFeature` does only exist on Windows server operating systems.

[source](https://learn.microsoft.com/en-us/windows/win32/wmisdk/win32-serverfeature)
> Instances of this class are not available on client computers

**Comment by joente** [comment]
Added v3.0.17-alpha0 for testing. In this version the "Win32_ServerFeature" is marked as optional.
